### ISSUE TITLE
SparkRuntimeException: [DUPLICATED_MAP_KEY]

### ISSUE THREAD

**Issue by mromanello** [dasmiq/passim#15]
Hello @dasmiq and @mutherr 👋

I've come across a strange bug when changing the default parameters of `seriatim`. Any thoughts you may have on how to fix it would be of great help at this stage in order to continue with my planned experiments. (I've checked and this error **does not occur** with passim v. 1 (pure Java implementation)).

The following commands run just fine on my data:
- `seriatim in.json out_cluster >& out_cluster.err`
- `seriatim -a 5 in.json out_cluster`

But whenever I try to change the value of `-n` or `--min-match` parameters, I run into a `SparkRuntimeException: [DUPLICATED_MAP_KEY]` (see full stack trace attached). I've tried the following commands and they all raise the same exception:
- `seriatim --min-match 3  in.json out_cluster`
- `seriatim --n 2 in.json out_cluster`

My system settings:
- Python v. 3.10.0
- `passim` v. 2.0.0a2
- Java v. `java 13.0.2 (2020-01-14)`

I'm attaching also the input file `in.json` for reproducibility purposes (NB: remove `.txt` extension after downloading the attached files). 
[in.json.txt](https://github.com/dasmiq/passim/files/11311475/in.json.txt)
[out_cluster.err.txt](https://github.com/dasmiq/passim/files/11311477/out_cluster.err.txt)

**Comment by dasmiq** [comment]
Hi @mromanello Sorry for the slow response. You caught me right at the end of term! This was a strange bug, but I think I've tracked it down. It looks like spark 3.4.0 introduced a bug in the map_from_arrays function that affected your data. Fortunately, it was only used incidentally in the code, so a workaround was easy. Check out the lates to the seriatim branch (7225bb81f5cfdc72a847a2c994b52efa679e3da7) and see if it works for you.
