### ISSUE TITLE
Converting to csv

### ISSUE THREAD

**Issue by jvdzwaan** [dasmiq/passim#2]
In the README you mention bash scripts `tabcluster.sh` and `csvcluster.sh`, but I am unable to locate them inside the repository. I did find the `dfconvert` script, but that one seems to be able to convert only single files (and not a directory of files). Am I missing something?

**Comment by dasmiq** [comment]
Thanks. I'd removed those options when Spark got native support for CSV. You could now use `--output-format csv` instead. I've removed the reference to those scripts from the README.

If you have existing output `dfconvert` will in fact work on whole directories. It uses, however, the hack that the input and output parent directory names should end with, e.g., `.json` or `.csv`.
