### ISSUE TITLE
exception when calling passim with multiple input paths

### ISSUE THREAD

**Issue by mromanello** [dasmiq/passim#8]
Hi @dasmiq 

I'm having issues while getting `passim` to accept comma-separated multiple input paths. 
When I run

```bash
passim --schema-path="impresso/passim.schema" \ 
impresso/data/GDL-1900.jsonl.bz2,impresso/data/GDL-1900.jsonl.bz2 passim-output
```

I get the following exception 
```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Path does not exist: file:/home/romanell/impresso_code/PH-passim-tutorial/impresso/data/GDL-1900.jsonl.bz2,impresso/data/JDG-1900.jsonl.bz2;
```

But the following command runs just fine:
```bash
passim --schema-path="impresso/passim.schema" impresso/data/*.jsonl.bz2 passim-output
```

Perhaps I misunderstood the syntax?

**Comment by dasmiq** [comment]
The spark and underlying hadoop path processing is very confusing. Although this isn't something that could be fixed within passim itself, using curly braces will fix this path ambiguity:
impresso/data/{GDL-1900.jsonl.bz2,GDL-1900.jsonl.bz2}

**Comment by dasmiq** [comment]
I fixed the README to use this more explicit syntax.
